




.build/uno/src/AnalogRead_DigitalRead/src/AnalogRead_DigitalRead.cpp : src/AnalogRead_DigitalRead/src/AnalogRead_DigitalRead.ino
	@mkdir -p .build/uno/src/AnalogRead_DigitalRead/src
	@echo [93msrc/AnalogRead_DigitalRead/src/AnalogRead_DigitalRead.ino[0m
	@/home/dafna/.local/bin/ino preproc  -o $@ $^

.build/uno/src/beep/src/sketch.cpp : src/beep/src/sketch.ino
	@mkdir -p .build/uno/src/beep/src
	@echo [93msrc/beep/src/sketch.ino[0m
	@/home/dafna/.local/bin/ino preproc  -o $@ $^

.build/uno/src/beep2/src/sketch.cpp : src/beep2/src/sketch.ino
	@mkdir -p .build/uno/src/beep2/src
	@echo [93msrc/beep2/src/sketch.ino[0m
	@/home/dafna/.local/bin/ino preproc  -o $@ $^

.build/uno/src/Blink_AnalogRead/Blink_AnalogRead.cpp : src/Blink_AnalogRead/Blink_AnalogRead.ino
	@mkdir -p .build/uno/src/Blink_AnalogRead
	@echo [93msrc/Blink_AnalogRead/Blink_AnalogRead.ino[0m
	@/home/dafna/.local/bin/ino preproc  -o $@ $^

.build/uno/src/GoldilocksAnalogueTestSuite/GoldilocksAnalogueTestSuite.cpp : src/GoldilocksAnalogueTestSuite/GoldilocksAnalogueTestSuite.ino
	@mkdir -p .build/uno/src/GoldilocksAnalogueTestSuite
	@echo [93msrc/GoldilocksAnalogueTestSuite/GoldilocksAnalogueTestSuite.ino[0m
	@/home/dafna/.local/bin/ino preproc  -o $@ $^


all : .build/uno/src/AnalogRead_DigitalRead/src/AnalogRead_DigitalRead.cpp .build/uno/src/beep/src/sketch.cpp .build/uno/src/beep2/src/sketch.cpp .build/uno/src/Blink_AnalogRead/Blink_AnalogRead.cpp .build/uno/src/GoldilocksAnalogueTestSuite/GoldilocksAnalogueTestSuite.cpp
	@true

